name: Automatic Labeling

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
  pull_request_review:
    types: [submitted]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Labels
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number: pull_number } = context.issue;
          const { data: pullRequest } = await github.rest.pulls.get({ owner, repo, pull_number });

          let label = '';
          console.log(`${pullRequest}`)
          if (pullRequest.draft) {
            label = 'wip';
          } else if (!pullRequest.draft) {
            label = 'reviews needed';
          } else if (pullRequest.mergeable_state === 'dirty') {
            label = 'merge conflicts';
          } else if (pullRequest.state === 'closed') {
            label = '';
          }else {
            const { data: reviews } = await github.rest.pulls.listReviews({ owner, repo, pull_number });
            const approved = reviews.some(review => review.state === 'APPROVED');
            const changesRequested = reviews.some(review => review.state === 'CHANGES_REQUESTED');
            if (approved) {
              label = 'merge me please';
            } else if (changesRequested) {
              label = 'changes requested';
            }
          }

          // list of labels to be removed
          const labelsToRemove = ['merge me please', 'reviews needed', 'merge conflicts', 'wip', 'changes requested'];

          // remove all label from list
          const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({ owner, repo, issue_number: pull_number });
          for (const { name } of currentLabels) {
            if (labelsToRemove.includes(name)) {
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number: pull_number,
                name
              });
            }
          }

          // add label
          if (label) {
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: pull_number,
              labels: [label]
            });
          }
